### ISSUE TITLE
Regularly occurs "Unexpected end of request content" error at JSNLogMiddleware.cs:line 38

### ISSUE THREAD

**Issue by neyromant** [mperdeck/jsnlog#102]
I am using jsnlog in the asp.net core application.
Very often, I receive an error "Unexpected end of request content" using both Kestrel and WebListener.

Stack trace:

An unhandled exception was thrown by the application.
System.AggregateException: One or more errors occurred. ---> System.IO.InvalidDataException: Unexpected end of request content
   at Microsoft.AspNet.Server.Kestrel.Http.MessageBody.ForContentLength.<ReadAsyncImplementation>d__3.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Microsoft.AspNet.Server.Kestrel.Http.FrameRequestStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.StreamReader.ReadBuffer()
   at System.IO.StreamReader.ReadToEnd()
   at JSNLog.JSNLogMiddleware.ProcessRequest(HttpContext context) in C:\dev\jsnlog\jsnlog\src\JSNLog\PublicFacing\AspNet5\LogRequestHandling\Middleware\JSNLogMiddleware.cs:line 70
   at JSNLog.JSNLogMiddleware.<Invoke>d__2.MoveNext() in C:\dev\jsnlog\jsnlog\src\JSNLog\PublicFacing\AspNet5\LogRequestHandling\Middleware\JSNLogMiddleware.cs:line 38
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.AspNet.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.AspNet.Hosting.Internal.HostingEngine.<>c__DisplayClass32_0.<<Start>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.AspNet.Server.Kestrel.Http.Frame.<RequestProcessingAsync>d__79.MoveNext()
---> (Inner Exception #0) System.IO.InvalidDataException: Unexpected end of request content
   at Microsoft.AspNet.Server.Kestrel.Http.MessageBody.ForContentLength.<ReadAsyncImplementation>d__3.MoveNext()<---
 One or more errors occurred.

**Comment by mperdeck** [comment]
My apologies for the very late reply.

Do you have a small test application that reproduces this problem? If so, could you make it available to me, such as on github? That way I can reproduce this and possibly find a solution.
