### ISSUE TITLE
Doesn't seem to like .NETCoreApp framework

### ISSUE THREAD

**Issue by MattJeanes** [mperdeck/jsnlog#129]
Hi, I've been trying the last few hours to get this working on the .NETCoreApp framework, as opposed to the normal NET Framework 4.5.2. Your [asp.net 5 demo](https://github.com/mperdeck/jsnlog.AspNet5Demo) uses 4.5.2 and when switching to .NET Core it just fails to work completely.

I ran into this because our project uses .NET Core and while the Startup.cs reference works fine and compiles okay we get a runtime error when loading a page, stack trace below. Interestingly the error happens if the JSNLog package is in the project.json, regardless of if it's actually referenced in Startup.cs or anywhere else.

```
System.InvalidOperationException: Can not find compilation library location for package 'JSNLog'
   at Microsoft.Extensions.DependencyModel.CompilationLibrary.ResolveReferencePaths()
   at System.Linq.Enumerable.<SelectManyIterator>d__159`2.MoveNext()
   at Microsoft.AspNetCore.Mvc.Razor.Compilation.MetadataReferenceFeatureProvider.PopulateFeature(IEnumerable`1 parts, MetadataReferenceFeature feature)
   at Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationPartManager.PopulateFeature[TFeature](TFeature feature)
   at Microsoft.AspNetCore.Mvc.Razor.Internal.RazorReferenceManager.GetCompilationReferences()
   at System.Threading.LazyInitializer.EnsureInitializedCore[T](T& target, Boolean& initialized, Object& syncLock, Func`1 valueFactory)
   at Microsoft.AspNetCore.Mvc.Razor.Internal.RazorReferenceManager.get_CompilationReferences()
   at Microsoft.AspNetCore.Mvc.Razor.Internal.DefaultRoslynCompilationService.CreateCompilation(String compilationContent, String assemblyName)
   at Microsoft.AspNetCore.Mvc.Razor.Internal.DefaultRoslynCompilationService.Compile(RelativeFileInfo fileInfo, String compilationContent)
   at Microsoft.AspNetCore.Mvc.Razor.Internal.RazorCompilationService.Compile(RelativeFileInfo file)
   at Microsoft.AspNetCore.Mvc.Razor.Internal.CompilerCache.CreateCacheEntry(String relativePath, String normalizedPath, Func`2 compile)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Razor.Internal.CompilerCache.GetOrAdd(String relativePath, Func`2 compile)
   at Microsoft.AspNetCore.Mvc.Razor.Internal.DefaultRazorPageFactoryProvider.CreateFactory(String relativePath)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.CreateCacheResult(HashSet`1 expirationTokens, String relativePath, Boolean isMainPage)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.OnCacheMiss(ViewLocationExpanderContext expanderContext, ViewLocationCacheKey cacheKey)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.LocatePageFromViewLocations(ActionContext actionContext, String pageName, Boolean isMainPage)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.FindView(ActionContext context, String viewName, Boolean isMainPage)
   at Microsoft.AspNetCore.Mvc.ViewEngines.CompositeViewEngine.FindView(ActionContext context, String viewName, Boolean isMainPage)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.ViewResultExecutor.FindView(ActionContext actionContext, ViewResult viewResult)
   at Microsoft.AspNetCore.Mvc.ViewResult.<ExecuteResultAsync>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeResultAsync>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextResultFilterAsync>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ResultExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at JSNLog.JSNLogMiddleware.<Invoke>d__2.MoveNext() in C:\dev\jsnlog\jsnlog\src\JSNLog\PublicFacing\AspNet5\LogRequestHandling\Middleware\JSNLogMiddleware.cs:line 43
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__6.MoveNext()
```

**Comment by MattJeanes** [comment]
Unfortunately I'm very new to .NET Core at the moment but if I find some time I might give it a bash. Cheers for the response though!

**Comment by pjvanhall** [comment]
Hi, 

I had the same issue.

I noticed after adding package 2.21.0 to my project that the references for JSNlog differd from the references in JSNLog.AspNetCore.nuspec . 

References project:
![image](https://cloud.githubusercontent.com/assets/11241763/21047464/5dd68176-be0a-11e6-943e-1aca07951493.png)

References JSNLog.AspNetCore.nuspec:
![image](https://cloud.githubusercontent.com/assets/11241763/21047515/9d22d0e6-be0a-11e6-8259-2f73f4e2bdb2.png)

So downloaded the solution and changed the project.json like this:
![image](https://cloud.githubusercontent.com/assets/11241763/21047619/301ddee0-be0b-11e6-9507-259d5a0953da.png)


Now it works but only if i add Jsnlog.dll to my bin/debug directory. I don't understand why i need to do this.

**Comment by mperdeck** [comment]
I've updated the references (to 2.22.0, the latest version).

I'm super busy at the moment. I probably won't be able to look into this issue until the new year.

**Comment by sikokimo** [comment]
I still have the same issue even in the demo, when i remove the "net452" framework from project.json 
i get the same exception.

**Comment by pandazzurro** [comment]
#137 Duplicate

**Comment by mperdeck** [comment]
I finally got it to work with .Net CORE again. Just released version 2.23.0 which works with version 1 of CORE.

**Comment by MattJeanes** [comment]
Does that include 1.1? I'll be sure to give it a go as soon as I can. Thanks!

**Comment by MattJeanes** [comment]
Just gave it a go, works great. Thanks very much.
